### ISSUE TITLE
Only let arp sequence arp patterns appear when it has a sequence

### ISSUE THREAD

**Issue by Dylan-Bolink** [rcrogers/yarns-loom#41]
Hi Chris,

I was thinking. Could it be possible to only let sequence arp patterns appear when the current part has a sequence?.
Otherwise the list would be very long and only after half way through it would contain patterns which will work if you don't have a sequence recorded

Not an issue more a feature request

**Comment by rcrogers** [comment]
Hey Dylan!  By having fewer patterns appear, you're referring to having
fewer options appear when scrolling through the values for the `ARP
PATTERN` setting, right?  Specifically, when no sequence exists, the 9
sequencer values (`S8`-`S0`) are hidden, and only the 23 pattern values are
available?

Clarification on the benefit/motivation here:
My current setup uses endless encoders in relative mode
(increment/decrement) for all CCs.  I'm guessing that you're sending
absolute CCs from pots (Needles only has pots, not encoders, I think?), and
so the pot's finite range/resolution is being wasted on setting values that
aren't relevant at the moment, i.e. you're effectively losing 1/3 of the
pot's range.  Is that the motivation for this change?

**Comment by Dylan-Bolink** [comment]
Hi Chris,

Thanks for your reaction. BTW nice to see you still working on the loom firmware i use it every day with Needles. Just started working on the needles again to get more out of it. Thinking of creating a Needles-Loom front panel at this point because practically everything has been changed from the panel...

You are indeed correct. It's about the arp pattern. Needles only uses standard pots and scrolling through the list is kind of finniky if you don't have a sequence recorded and just want the standard pattern. If the S patterns aren't there it would be just a matter of turning the pot fully counter clockwise instead of somewhere at 10/11 o clock. I can do this at Needles end with some knob scaling maybe but i think it would be nicer to do it in Loom firmware because Needles doesn't actually know if there is a sequence recorded or not (can only do guess work of course) Not only Needles but every midi controller ;) 

Kind regards and again super thanks for all your work.

**Comment by rcrogers** [comment]
Hi @Dylan-Bolink!  This should be fixed in [2.7.1](https://github.com/rcrogers/yarns-loom/releases/tag/v2.7.1).  Let me know how it's working when you get a chance!

**Comment by Dylan-Bolink** [comment]
Hi @rcrogers i will check it out tonight many thanks for your work.

Small question: 
the cc setting "Portamento legato only off/on"
On means that it will only slide/portamento when you play it legato?
And the other setting handles the retrigger right?

**Comment by rcrogers** [comment]
Yes, if `PORTAMENTO LEGATO ONLY` is `ON`, portamento will only be applied to notes played legato.  If it's `OFF`, portamento will be applied to all notes, legato or not.

**Comment by Dylan-Bolink** [comment]
Hi @rcrogers 

If i install the update my yarns is getting really slow and the screen starts flickering. Tried installing it again but same result. When i revert back to 2.7.0 it's all normal again.

Any idea on what this could be?

**Comment by rcrogers** [comment]
Could you try redownloading the firmware file?  I redid the build -- I've seen bad builds do that before.

**Comment by Dylan-Bolink** [comment]
Thanks for the quick reaction! It worked many thanks :) the Feature request is also working.
Thanks for all your work on this firmware.

**Comment by rcrogers** [comment]
Glad to hear, you're very welcome and thanks for testing!
